### ISSUE TITLE
Bring in PDL::IO::GD history from PDL repo

### ISSUE THREAD

**Issue by zmughal** [PDLPorters/pdla-io-gd#2]

**Comment by mohawk2** [comment]
The steps for this are:
- make sure git-subtree is installed and works (if not, get from https://github.com/git/git/blob/master/contrib/subtree/git-subtree.sh and place with +x in `/usr/local/libexec/git-core/git-subtree`)
- `cd $PDLREPODIR`
- `git subtree split -P IO/GD -b p-i-g`
- `cd $PIGDIR`
- `git pull $PDLREPODIR p-i-g`
