### ISSUE TITLE
pdl-io-gd split tasks

### ISSUE THREAD

**Issue by zmughal** [PDLPorters/pdla-io-gd#3]
- [x] standalone `Makefile.PL`: [done](https://github.com/PDLPorters/pdl-io-gd/commit/7b6a6a1c6f4a8ce73c71bbdcdd325abf68bd5647)
- [x] add repository info to metadata: [done](https://github.com/PDLPorters/pdl-io-gd/commit/03e152554da29f0a50db4688aed55ab0f19ecade)
- [x] make sure PDL tests for this module are available: [done](https://github.com/PDLPorters/pdl-io-gd/commit/2a5f7668266f685f1e7da9230bf7bba467f4e9c3)
- [x] check that Travis-CI builds work: [done](https://github.com/PDLPorters/pdl-io-gd/commit/db9b124982c34ad4464a058da2bfefaf0d1b2a6d)
- [ ] check that Appveyor builds work
- [x] add badges to README (coverage, etc.): done in #4
- [x] prep `Changes` for new version. Make note that the next release is its own repo and distro: [done](https://github.com/PDLPorters/pdl-io-gd/commit/5f32c4c9ba4c83ea07ce006aa8ff87898a774614)
- [x] add `xt/00-check-changelog.t` test: [done](https://github.com/PDLPorters/pdl-io-gd/commit/25c6f08494677ecdd053762016b3ae54b7a4a933)
- [x] add `.gitignore`: [done](https://github.com/PDLPorters/pdl-io-gd/commit/988f8e6da9a63ad8a56ea22d95326660796a582f)
- [ ] add a test to check that `pdldoc` indexing works for the new dist
- [ ] make sure all the configuration options for BAD values are tried by Travis-CI (settings are in `perldl.conf`)

[pdl split meta-issue](https://github.com/PDLPorters/pdl/issues/119)

**Comment by devel-chm** [comment]
A key issue for modules that have been split out from the PDL 
distribution is to make sure that the hooks needed to update the PDL 
online docs database are correct.  Otherwise the module will be 
"invisible" to the pdldoc/help/apropos commands.  What might make sense 
is to split out PDL::Core and then check the other split out modules 
using that rather that the bulk distribution (although it should work 
there as well)

**Comment by mohawk2** [comment]
This might need a rethink of how the pdldoc stuff works.

**Comment by zmughal** [comment]
Very good points. We'll need to add a test to make sure that this always works no matter how we may build the pdldoc database in the future. Better to check breakage first in dev.

Perhaps we can add a standard hook for what PDL-Stats does with its [`add_doc.pl`](https://metacpan.org/source/MAGGIEXYZ/PDL-Stats-0.6.5/add_doc.pl)?

**Comment by devel-chm** [comment]
A standard hook sounds like the right direction.  I'm with Ed that we might
want to rethink the pdldoc a little bit.  The current add_doc.pl works but
seems a bit hackish.  It would be nice to have something a little clearer,
simpler, maybe even automatic/transparent...

--Chris

**Comment by zmughal** [comment]
I was looking online for past discussion and saw that you [commented](http://comments.gmane.org/gmane.comp.lang.perl.pdl.general/6272) that 

> It would be nice if the implementation could be
> made more modular (e.g., you could compose the
> docs from multiple database files somehow, undo
> changes,...).

We can do that now! If we are doing a split, then now would be the perfect time to look into that.

**Comment by mohawk2** [comment]
I think that add_doc.pl is very similar to the code in PDL::Doc's "EXAMPLE". What this tells me is we just need an extra bit of API to encapsulate this. Shouldn't be hard. Thoughts?

**Comment by mohawk2** [comment]
Re @zmughal 's quote of a previous remark by @devel-chm , let's not get overcomplicated. I think adding docs that can then be found in the same way as now, i.e. preserving current functionality under the new scheme is enough. What do you guys think?

**Comment by devel-chm** [comment]
I think keeping it minimal---just enough to maintain the pdldoc status quo
while we divest the PDL distribution makes sense.  However, it would be
nice if there were something a bit less magical than adding mysterious
lines by hand..

**Comment by zmughal** [comment]
Right, doing it the same way will get the release out the door faster without backcompat issues.

And if we do add a hook to PDL::Core, it will already know where the database file is so all it needs to know is the path to scan, correct?

**Comment by mohawk2** [comment]
I assume you mean PDL::Doc, not PDL::Core? It will work in the same way as currently, but hide the detail that is currently revealed/required.

**Comment by zmughal** [comment]
Yes, @mohawk2. See the issue I created here https://github.com/PDLPorters/pdl-core/issues/2.

There are only 2 modules that use the `scan` interface. The rest use the already existing `add_module` function.

**Comment by mohawk2** [comment]
A suitably minimal (4-line) fix that makes PDL::IO::GD "just work" in pdldoc: https://github.com/PDLPorters/pdl/pull/122 - though it will need a suitably up-to-date PDL once we release this.

**Comment by zmughal** [comment]
To replicate the process I've been using to check if this would work with a dep on just `PDL::Core`, run:

``` shell
git clone -b pdl-core-only https://github.com/PDLPorters/pdl.git
cd pdl
perl Makefile.PL && make test && make install

cd ..

git clone https://github.com/PDLPorters/pdl-io-gd.git
cd pdl-io-gd
perl Makefile.PL && make test && make install
```

Just a note: `PDL::IO::GD` depends on `PDL::IO::Misc` as well as `PDL::Core`.

**Comment by mohawk2** [comment]
Wow, nice research. May I suggest a follow-up or edit of the above to be a full perlbrew snippet that those reading along at home can try out / see the results of?

**Comment by zmughal** [comment]
Feel free!
